//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zerohungerv2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRIBUTION_RCRD
    {
        public int D_ID { get; set; }
        public int F_ID { get; set; }
        public System.DateTime DISTRIBUTE_DATE { get; set; }
        public string RECIPIENT { get; set; }
        public int QT_DISTRIBUTE { get; set; }
    
        public virtual FOOD_ITEM FOOD_ITEM { get; set; }
    }
}
