//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zerohungerv2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOOD_ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FOOD_ITEM()
        {
            this.DISTRIBUTION_RCRD = new HashSet<DISTRIBUTION_RCRD>();
        }
    
        public int F_ID { get; set; }
        public int C_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<System.DateTime> EXPIRY { get; set; }
    
        public virtual COLLECT_RQST COLLECT_RQST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISTRIBUTION_RCRD> DISTRIBUTION_RCRD { get; set; }
    }
}
