//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zerohungerv2.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGO_EMP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGO_EMP()
        {
            this.COLLECT_RQST = new HashSet<COLLECT_RQST>();
        }
    
        public int E_ID { get; set; }
        public string E_NAME { get; set; }
        public string E_CONTACT { get; set; }
        public string ROLE { get; set; }
        public string E_PASS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLLECT_RQST> COLLECT_RQST { get; set; }
    }
}
